stages:
  - changelog

update_changelog:
  stage: changelog
  image: python:3.12
  script:
    - pip install .
    - smart-changelog update
    - git config user.email "bot@company.com"
    - git config user.name "SmartChangelog Bot"
    - git add CHANGELOG.md
    - git commit -m "chore: update changelog [skip ci]" || echo "No changes"
    - git push origin HEAD:main
  only:
    - main
