stages:
  - changelog

update_changelog:
  stage: changelog
  image: python:3.12
  script:
    - pip install .
    - rm -rf build smart_changelog.egg-info
    - |
        if [ -f .env ]; then
          set -a
          . ./.env
          set +a
        fi
        : "${JIRA_URL:?JIRA_URL must be set}"
        if [ -z "${JIRA_TOKEN}" ] && { [ -z "${JIRA_EMAIL}" ] || [ -z "${JIRA_API_TOKEN}" ]; }; then
          echo "Jira credentials not set (provide JIRA_TOKEN or JIRA_EMAIL/JIRA_API_TOKEN)" >&2
          exit 1
        fi
        SMART_CHANGELOG_SKIP_COMMIT=1 smart-changelog update
    - git config user.email "bot@company.com"
    - git config user.name "SmartChangelog Bot"
    - git add CHANGELOG.md
    - git commit -m "chore: update changelog [skip ci]" || echo "No changes"
    - git push origin HEAD:main
  only:
    - main
